### ISSUE TITLE
Review Security Checklist

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1288]
From [the security checklist](https://wiki.mozilla.org/Security/CloudSec#Security_Checklist):

# Infrastructure rules

* [ ] Use modern TLS (INFRA-TLS)
* [ ] Set HSTS to 2592000 (30 days) (INFRA-HSTS)
* [ ] Set HPKP to 2592000 (30 days) (INFRA-HPKP)
  * **Note:** all these are to be done by ops.
* ~~Admin panels must: ...~~
  * **Note:** we have no admin panel

# Coding rules

The following rules apply to all web applications: api and websites.

* [x] Detailed logging in mozlog format (APP-MOZLOG)
  * **Note:** see #1188 
  * [ ] Business logic must be logged with app specific codes (errno)
  * [ ] Access control failures must be logged at WARN level
* [x] All SQL queries must be parameterized, not concatenated (APP-SQL)
* [x] User data must be escaped for the right context prior to reflecting it (APP-ESCAPE)
* [x] Apply sensible limits to user inputs, see Input validation (APP-INPUTVAL)
* [x] Enforce Access Controls server-side (APP-ACL)
  * **Note:** done in [server.js](https://github.com/mozilla-services/pageshot/blob/master/server/src/server.js)
* [x] Set the Secure flag on Cookies, and use sensible Expiration and HTTPOnly (APP-SECCOOKIE)
* [ ] Keep 3rd-party libraries up to date (APP-DEPS)
  * [ ] Use NSP or Greenkeeper for NodeJS applications
    * **Note:** see #802
  * ~~Use pip --outdated or requires.io for Python applications~~
    * **Note:** no Python dependencies
* [ ] When handling cryptographic keys, must have a mechanism to handle monthly key rotations (APP-KEYROT)
  * **Note:** we [support a key rotation](https://github.com/mozilla-services/pageshot/blob/19856a3a7d47ffb129cd4f7e8cac8f51e5d1c812/server/src/dbschema.js#L95) in our database, but haven't implemented any rotation mechanism or process for making those rotations.

# For websites

The following coding rules only apply to websites.

* [x] Never store passwords, use Firefox Accounts (APP-IDP)
  * **Note**: We do have passwords or any account currently
* [ ] Forbid Mixed content, always use HTTPS (APP-MIXCONTENT)
* [x] Must have a CSP with (APP-CSP)
  * **Note:** See #1289
  * [ ] a report-uri pointing to the service /__cspreport__
  * [ ] frame-options set to deny
  * [x] no use of unsafe-inline or unsafe-eval
* [x] Must have CSRF tokens and manually excluded specific forms (APP-CSRF)
  * **Note:** We have no HTML forms
* [ ] Must have checksums for 3rd-party content via SRI (APP-SRI)
  * **Note:** The only 3rd party content we have is Google Analytics, we're not sure how to handle that.
* [ ] Consider Security headers as appropriate (APP-HEADERS)
  * [ ] X-Content-Type-Options
  * [ ] X-Frame-Options
  * [ ] X-XSS-Protection

# Data rules

**Note:** we don't follow these items in the checklist, per design and as documented in the Risk Assessment.

* ~~Sensitive user data (like browsing history) stored on our servers must either be:~~
  * ~~Anonymized (similar to Tiles) (DATA-ANON)~~
  * ~~Encrypted client-side (similar to Sync) (DATA-CRYPT)~~
* Must sign data and code pushed to Firefox clients (DATA-SIGN)
  * [x] Addons must use standard AMO signing (APP-SIGNING)
    * **Note:** we create a signed Add-on
  * [ ] Code & Conf must use Content-Signature via Autograph (DATA-SIGNING)
* ~~Must implement a sign-off protocol when changing data/code to the beta and release channels, see Firefox Continuous Delivery Sign Off~~
  * **Note:** We do not ship directly to beta or release.

**Comment by pdehaan** [comment]
Not sure if this is worth a separate bug, but looking at `https://github.com/mozilla/testpilot/issues/1311`, this looks pretty interesting:

https://observatory.mozilla.org/analyze.html?host=pageshot.net

<img width="614" alt="observatory_by_mozilla" src="https://cloud.githubusercontent.com/assets/557895/18330409/41b5bdf4-750d-11e6-9cde-9db1d27fd931.png">

**Comment by ianb** [comment]
It might be better to run this on a shot page, the homepage is a bit of an oddball page.  But I'm failing to get a shot URL right now because of login problems on pageshot.net.

I'm pretty sure we need to do HSTS, but should consult ops / @relud.  I think we do X-Content-Type-Options on shot pages.  We should probably do X-Frame-Options.  Subresource integrity seems like more trouble than its worth.

**Comment by pdehaan** [comment]
I think Observatory may only support top level domain. It seems to be choking on the `/` in any URL. /cc @jvehent 

<img width="704" alt="observatory_by_mozilla" src="https://cloud.githubusercontent.com/assets/557895/18331182/d34bc890-7511-11e6-821a-bf9f3aa62502.png">

**Comment by jvehent** [comment]
@marumari handles that. We run a separate scanner to evaluate the baseline. Here are the results: https://raw.githubusercontent.com/wiki/mozilla-services/cloudsec/baseline-results/pageshot.net/2016-09-05?token=AAZXgaQN7d0x7aTc9UsdLHiXbwVJNLxrks5X2dfGwA%3D%3D

**Comment by marumari** [comment]
@pdehaan: The observatory can in fact handle URLs -- it only supports top-level domains, but it will extract those -- but it needs to be a valid URL.  :)

**Comment by marumari** [comment]
Also it doesn't yet support scanning subpages, but it's way up towards the top of my list to add support for.

**Comment by ianb** [comment]
Closing this out.

I'd added #1496 and #1497 for HSTS and X-Frame-Options.

I added #1498 for CSP report, but haven't prioritized it.

The cookie library we use defaults to using httpOnly and secure.  The cookies are session cookies (no expiration).
