### ISSUE TITLE
Release Deneb Checklist

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2032]
For release we should:
- [x] Bump version number to "4.0.0"
- [x] Update changelog
- [x] Create tag
- [x] Confirm [Docker Hub](https://hub.docker.com/r/mozilla/pageshot/tags/) has the right tag
- [x] Create Bugzilla ticket.  Copy [Bug 1321340](https://bugzilla.mozilla.org/show_bug.cgi?id=1321340)
- [x] **Note `CONTROLLER_SINGLETON`**: this variable should be true on one and only one server instance
- [x] Generate pageshot.net add-on and get it deployed on testpilot site
- [x] Run `bin/load_test_exercise.py --times 100 https://pageshot.stage.mozaws.net`
- [x] Post to [Discourse](https://discourse.mozilla-community.org/c/test-pilot/page-shot)
- [x] Create GitHub release
- [x] Note release in GA as annotation
- [x] Close Deneb milestone
- [x] Make a copy of this ticket for the next release
- [x] Create bug in next milestone to run `npm outdated`
