### ISSUE TITLE
Release Fafnir Checklist

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2137]
For release we should:
- [ ] Update changelog: `./bin/generate-commit-log --write stable..master`
- [ ] Bump version number to "6.0.0": `./bin/commit-new-version`
- [ ] Release to dev and stage, `./bin/release-version dev` (then upload) and `./bin/release-version stage` (automatic)
- [ ] Run `bin/load_test_exercise.py --times 100 https://pageshot.stage.mozaws.net`
- [ ] Create Bugzilla ticket.  [Copy Bug 1321340](https://bugzilla.mozilla.org/enter_bug.cgi?format=__default__&cloned_bug_id=1321340&product=Cloud%20Services&component=Operations)
- [ ] Generate prod XPI, `./bin/release-version prod` (then email to Wil)
- [ ] Post to [Discourse](https://discourse.mozilla-community.org/c/test-pilot/page-shot)
- [ ] Create GitHub release
- [ ] Note release in GA as annotation
- [ ] Close Fafnir milestone
- [ ] Make a copy of this ticket for the next release
- [ ] Create bug in next milestone to run `npm outdated` and `npm run nsp`
- [ ] Update the [optimization backlog](https://docs.google.com/spreadsheets/d/1nlyBmk5exIQvh4syySSEZGJSEhLLgXbr9pOwmfwrKKE/edit#gid=0) with dates for any experiments that have been deployed

**Comment by ianb** [comment]
Closing because we aren't releasing Fafnir
